DROP TABLE IF EXISTS USERS; --Done
DROP TABLE IF EXISTS DOCUMENTS;

CREATE TABLE "USERS" (
    "USER_ID" INTEGER IDENTITY NOT NULL PRIMARY KEY, 
    "COMMENT" VARCHAR(255) NOT NULL, 
    "USERNAME" VARCHAR(255) NOT NULL
);

CREATE TABLE "DOCUMENTS" (
    "USER_ID" INTEGER NOT NULL,
    "DOC_ID" INTEGER IDENTITY NOT NULL, 
    "CONTENT" VARCHAR(255) NOT NULL
);